BlogApp.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using BlogApp.WebUI.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IBlogRepository _blogRepository;

        public HomeController(IBlogRepository blogRepository)
        {
            _blogRepository = blogRepository;
        }
        public IActionResult Index(int? id)
        {
            var viewmodel = new HomeBlogViewModel();

            var homeBlogs = _blogRepository.GetAll().Where(u => u.isApproved && u.isHome);
            viewmodel.SliderBlogs = _blogRepository.GetAll()
                .Where(u => u.isApproved && u.isSlider).OrderByDescending(p => p.Date).ToList();

            if (id != null)
                viewmodel.HomeBlogs = homeBlogs.Where(p => p.CategoryId == id)
                    .OrderByDescending(p => p.Date).ToList();
            else
                viewmodel.HomeBlogs = homeBlogs.OrderByDescending(p => p.Date).ToList();

            return View(viewmodel);
        }
        public IActionResult List()
        {
            return View();
        }
        public IActionResult Details(int id)
        {
            var blog = _blogRepository.GetById(id);
            if(blog == null || blog.isApproved==false || blog.isHome==false)
                return View("Error");

            return View(_blogRepository.GetById(id));

        }
    }
}

BlogApp.WebUI/ViewComponents/CategoryMenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace BlogApp.WebUI.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private ICategoryRepository _categoryRepository;

        public CategoryMenuViewComponent(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["id"];
            return View(_categoryRepository.GetAll());
        }
    }
}

BlogApp.WebUI/Views/Home/Details.cshtml
@model Blog
@{
    ViewData["Title"] = "Details";
}

    <div class="container mt-3">
        <div class="row">

            <div class="col-md-8">
                <div class="card ">
                    <div class="card-header">
                        @Model.Title
                    </div>
                    <img class="card-img-top" src="~/img/@Model.Image" alt="Card image cap">

                    <div class="card-block">
                        <h4 class="card-title">@Model.Description</h4>
                        <p class="card-text">@Model.Body</p>
                        <a asp-action="Index" class="btn btn-primary">Geri Git</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                @await  Component.InvokeAsync("CategoryMenu")
            </div>
        </div>
    </div>

BlogApp.WebUI/Views/Home/Index.cshtml
@model HomeBlogViewModel
@{
    ViewData["Title"] = "Index";
}

<div class="container my-4">
    <div class="row">

        <div class="col-md-8">
            <partial name="_Slider" model="Model.SliderBlogs"/>
            <partial name="_BlogList" model="Model.HomeBlogs"/>

        </div>
        <div class="col-md-4">
            @await  Component.InvokeAsync("CategoryMenu")
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Home/List.cshtml
@{
    ViewData["Title"] = "List";
}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-8">
            <div class="card ">
                <div class="card-header">
                    Featured
                </div>
                <img class="card-img-top" src="~/img/1.jpeg" alt="Card image cap">

                <div class="card-block">
                    <h4 class="card-title">Special title treatment</h4>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
            <div class="card mt-2">
                <div class="card-header">
                    Featured
                </div>
                <img class="card-img-top" src="~/img/2.jpeg" alt="Card image cap">

                <div class="card-block">
                    <h4 class="card-title">Special title treatment</h4>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
            <div class="card mt-2">
                <div class="card-header">
                    Featured
                </div>
                <img class="card-img-top" src="~/img/3.jpeg" alt="Card image cap">

                <div class="card-block">
                    <h4 class="card-title">Special title treatment</h4>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
            <div class="card mt-2">
                <div class="card-header">
                    Featured
                </div>
                <img class="card-img-top" src="~/img/4.jpeg" alt="Card image cap">

                <div class="card-block">
                    <h4 class="card-title">Special title treatment</h4>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="list-group">
                <a href="#" class="list-group-item active">
                    Cras justo odio
                </a>
                <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
                <a href="#" class="list-group-item list-group-item-action">Morbi leo risus</a>
                <a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
                <a href="#" class="list-group-item list-group-item-action disabled">Vestibulum at eros</a>
            </div>
        </div>
    </div>
</div>