BlogApp.WebUI/Controllers/BlogController.cs
using System.Linq;
using BlogApp.Data.Abstract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogApp.WebUI.Controllers
{
    public class BlogController : Controller
    {
        private IBlogRepository _blogRepository;

        public BlogController(IBlogRepository blogRepository)
        {
            _blogRepository = blogRepository;
        }

        public IActionResult Index(int? id, string q)
        {
            var query = _blogRepository.GetAll().Where(p => p.isApproved);

            if (id != null)
            {
                // id bos degilse kategorisel süzme var demektir.
                query = query.Where(p => p.CategoryId == id);
            }

            if (!string.IsNullOrEmpty(q))
            {
                //İlk Arama Şekli
                //query = query.Where(p => p.Title.Contains(q) || p.Description.Contains(q) || p.Body.Contains(q));

                //EF CORE ILE GELEN OZELLIK - DAHA OZEL ARAMALAR YAPABILIRIZ
                query = query.Where(p => EF.Functions.Like(p.Title, "%" + q + "%") ||
                EF.Functions.Like(p.Description, "%"+q+"%") || 
                EF.Functions.Like(p.Body, "%"+q+"%"));
            }

            return View(query.OrderByDescending(p => p.Date));

        }

        public IActionResult Details(int id)
        {
            var blog = _blogRepository.GetById(id);
            if (blog == null || blog.isApproved==false)
                return View("Error");

            return View(_blogRepository.GetById(id));

        }
    }
}

BlogApp.WebUI/Controllers/PanelController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using BlogApp.Data.Abstract;
using BlogApp.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BlogApp.WebUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PanelController : Controller
    {
        private IPanelRepository _panelRepository;
        private ICategoryRepository _categoryRepository;

        public PanelController(IPanelRepository panelRepository, ICategoryRepository categoryRepository)
        {
            _panelRepository = panelRepository;
            _categoryRepository = categoryRepository;
        }
        //public IActionResult Index()
        //{
        //    return View();
        //}

        public IActionResult List()
        {
            return View(_panelRepository.GetAll());
        }

        public async Task<IActionResult> Delete(int id)
        {
            var blogTitle = _panelRepository.GetById(id).Title;
            _panelRepository.DeleteBlog(id);
            try
            {
                if (await _panelRepository.SaveChangesAsync())
                {
                    TempData["message"] = $"{blogTitle} başarıyla silindi.";
                }
            }
            catch (Exception error)
            {
                TempData["message"] = $"{blogTitle} adlı blog silinemedi. Hata mesajı : {error.Message}";

            }
            return RedirectToAction("List");

        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Blog entity)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    _panelRepository.SaveBlog(entity);
                    if (await _panelRepository.SaveChangesAsync())
                    {
                        TempData["message"] = "Kayıt başarıyla güncellendi";
                        return RedirectToAction("List");
                    }
                }
                catch (Exception error)
                {
                    TempData["message"] = $"Blog kaydedilirken hata oluştu. Hata mesajı : {error.Message}";
                    return View(entity);
                }
            }

            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
            return View(entity);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
            return View(_panelRepository.GetById(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Blog entity, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }

                    entity.Image = file.FileName;
                }

                _panelRepository.SaveBlog(entity);
                try
                {
                    if (await _panelRepository.SaveChangesAsync())
                    {
                        TempData["message"] = "Kayıt başarıyla güncellendi";
                        return RedirectToAction("List");
                    }
                }
                catch (Exception error)
                {
                    TempData["message"] = $"Blog kaydedilirken hata oluştu. Hata mesajı : {error.Message}";
                    return View(entity);
                }
            }
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
            return View(entity);
        }

    }
}

BlogApp.WebUI/Views/Panel/Create.cshtml
@model Blog
@{
    ViewData["Title"] = "Create Blog";
    Layout = "_AdminLayout";
}

<div class="container mt-3">

    <h2>Create Blog</h2>
    <hr />
    <form asp-action="Create" asp-controller="Panel" method="post">
        <div class="form-group">
            <label asp-for="Title">Blog Title</label>
            <input asp-for="Title" class="form-control" placeholder="Enter blog title">
        </div>
        <div class="form-group">
            <label asp-for="Description">Description</label>
            <input asp-for="Description" class="form-control" placeholder="Enter blog description">
        </div>
        <div class="form-group">
            <label asp-for="Body">Blog Body</label>
            <textarea asp-for="Body" class="form-control" placeholder="Enter blog body"></textarea>
        </div>

        <div class="form-group">
            <label asp-for="CategoryId">Category</label>
            <select class="form-control" asp-for="CategoryId" asp-items="ViewBag.Categories">
                <option selected disabled value="">Select Category</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Create Blog</button>
    </form>
</div>

BlogApp.WebUI/Views/Panel/Edit.cshtml
@model Blog
@{
    ViewData["Title"] = "Edit Blog";
    Layout = "_AdminLayout";
}

@section scripts{

    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("Body")
    </script>
}

<div class="container mt-3">

    <h2>Edit Blog</h2>
    <hr />
    <form asp-action="Edit" asp-controller="Panel" method="post" enctype="multipart/form-data">
        <input type="hidden" asp-for="BlogId" />
        <input type="hidden" asp-for="Image" />
        <div class="form-group">
            <label asp-for="Title">Blog Title</label>
            <input asp-for="Title" class="form-control" placeholder="Enter blog title">
        </div>
        <div class="form-group">
            <label asp-for="Description">Description</label>
            <input asp-for="Description" class="form-control" placeholder="Enter blog description">
        </div>
        <div class="form-group">
            <label asp-for="Body">Blog Body</label>
            <textarea asp-for="Body" class="form-control" placeholder="Enter blog body"></textarea>
        </div>
        <div class="row">
            <div class="form-group col-md-2 col-sm-6">
                <img src="~/img/@Model.Image" width="170" height="80" />
            </div>
            <div class="form-group col-md-10 col-sm-6">
                <label asp-for="Image">Select Image</label>
                <input type="file" name="file" id="file" class="form-control">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-3">
                <label asp-for="CategoryId">Category</label>
                <select class="form-control" asp-for="CategoryId" asp-items="ViewBag.Categories">
                    <option selected disabled value="">Select Category</option>
                </select>
            </div>
            <div class="form-group col-md-3">
                <label asp-for="isApproved">Yayınlama Durumu</label>
                <select class="form-control" asp-for="isApproved">
                    <option selected disabled value="">Yayın Durumu</option>
                    <option value="true">Yayında</option>
                    <option value="false">Yayında Değil</option>
                </select>
            </div>
            <div class="form-group col-md-3">
                <label asp-for="isHome">Anasayfa İçeriği</label>
                <select class="form-control" asp-for="isHome">
                    <option selected disabled value="">Anasayfa Gösterim Durumu</option>
                    <option value="true">Gösterimde</option>
                    <option value="false">Gösterimde Değil</option>
                </select>
            </div>
            <div class="form-group col-md-3">
                <label asp-for="isSlider">Slider İçeriği</label>
                <select class="form-control" asp-for="isSlider">
                    <option selected disabled value="">Slider Gösterim Durumu</option>
                    <option value="true">Gösterimde</option>
                    <option value="false">Gösterimde Değil</option>
                </select>
            </div>

        </div>

        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>

BlogApp.WebUI/Views/Panel/List.cshtml
@model IEnumerable<Blog>
@{
    ViewData["Title"] = "List";
    Layout = "_AdminLayout";
}


<div class="container mt-3">
    <h2>Blog List</h2>
    <hr />
    <div class="row">
        <div class="col">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Resim</th>
                            <th>Başlık</th>
                            <th>Kayıt Tarihi</th>
                            <th>Yayın ?</th>
                            <th>Anasayfa ?</th>
                            <th>Slider ?</th>
                            <th></th>
                        </tr>  
                    </thead>
                    <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="align-middle">
                            <td class="align-middle">@item.BlogId</td>
                            <td class="align-middle">
                                <img src="~/img/@item.Image" alt="@item.Image" width="100" />
                            </td>
                            <td class="align-middle">@item.Title</td>
                            <td class="align-middle">@item.Date</td>
                            <td class="align-middle">
                                @if (item.isApproved)
                                {
                                    <i class="fa fa-check"></i>
                                }
                                else
                                {
                                    <i class="fa fa-times"></i>
                                }
                            </td>
                            <td class="align-middle">
                                @if (item.isHome)
                                {
                                    <i class="fa fa-check"></i>
                                }
                                else
                                {
                                    <i class="fa fa-times"></i>
                                }
                            </td>
                            <td class="align-middle">
                                @if (item.isSlider)
                                {
                                    <i class="fa fa-check"></i>
                                }
                                else
                                {
                                    <i class="fa fa-times"></i>
                                }
                            </td>
                            <td class="align-middle">
                                <a class="btn btn-primary btn-sm" asp-action="Details" asp-controller="Blog" asp-route-id="@item.BlogId">Preview</a>
                                <a class="btn btn-success btn-sm" asp-action="Edit" asp-controller="Panel" asp-route-id="@item.BlogId">Edit</a>
                                <a class="btn btn-danger btn-sm text-white delete"
                                   data-id="@item.BlogId"
                                   data-controller="Panel"
                                   data-action="Delete"
                                   data-body-message="Are you sure to delete this blog?">
                                    Delete
                                </a>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-danger">
                    Blog eklenmemiş
                </div>
            }
        </div>
    </div>
</div>